### ISSUE TITLE
Update docker images in GL GPU example and in repo

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml.dev#164]
In repo

```yaml
deploy_job:
  image: dvcorg/cml

job:
  image: dvcorg/cml-py3
```

in web
```
deploy_job:  
    image: dvcorg/cml

 train_job:
  image: iterativeai/cml:0-dvc2-base1-gpu
```

both cases should be 

```yaml
deploy_job:
  image: iterativeai/cml:0-dvc2-base1

job:
  image: iterativeai/cml:0-dvc2-base1-gpu
```
