### ISSUE TITLE
Multiple spaces in each line when "Copy" workflow yaml 

### ISSUE THREAD

**Issue by dmpetrov** [iterative/cml.dev#25]
When I copy the yaml and past it in vi/Notes it creates additional spaces in every single line like:

```yaml
name: train-my-model



on: [push]



jobs:

  run:

    runs-on: [ubuntu-latest]

    container: docker://dvcorg/cml-py3:latest

    steps:

      - uses: actions/checkout@v2

      - name: cml_run

        env:

          repo_token: ${{ secrets.GITHUB_TOKEN }}

        run: |

          pip3 install -r requirements.txt

          python train.py



          cat metrics.txt >> report.md

          cml-publish confusion_matrix.png --md >> report.md

          cml-send-comment report.md



```
